### ISSUE TITLE
Unable to reproduce market2017 when training from scratch

### ISSUE THREAD

**Issue by zye1996** [KaiyangZhou/deep-person-reid#490]
Hi I am modifying the models based on osnet so I decided to train osnet from scratch to compare apple to apple. I am trying to reproduce the performance on market2017 as stated in paper, and get the result as below:

![image](https://user-images.githubusercontent.com/28901953/152029471-cbf75b67-3e79-400e-9517-f8bfec6e02fe.png)

It is far from stated in the paper (mAP 81.0) so I am wondering if I have missed anything in the configuration

```
adam:
  beta1: 0.9
  beta2: 0.999
cuhk03:
  classic_split: False
  labeled_images: False
  use_metric_cuhk03: False
data:
  combineall: False
  height: 256
  k_tfm: 1
  load_train_targets: False
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  root: data
  save_dir: log/osnet_x1_0_market1501_softmax_sgd
  sources: ['market1501']
  split_id: 0
  targets: ['market1501']
  transforms: ['random_flip']
  type: image
  width: 128
  workers: 4
loss:
  name: softmax
  softmax:
    label_smooth: True
  triplet:
    margin: 0.3
    weight_t: 1.0
    weight_x: 0.0
market1501:
  use_500k_distractors: False
model:
  fusion: 
  load_weights: 
  name: osnet_x1_0
  pretrained: False
  resume: 
rmsprop:
  alpha: 0.99
sampler:
  num_cams: 1
  num_datasets: 1
  num_instances: 4
  train_sampler: RandomSampler
  train_sampler_t: RandomSampler
sgd:
  dampening: 0.0
  momentum: 0.9
  nesterov: False
test:
  batch_size: 300
  dist_metric: euclidean
  eval_freq: 10
  evaluate: False
  normalize_feature: False
  ranks: [1, 5, 10, 20]
  rerank: False
  start_eval: 0
  visrank: False
  visrank_topk: 10
train:
  base_lr_mult: 0.1
  batch_size: 64
  fixbase_epoch: 0
  gamma: 0.1
  lr: 0.065
  lr_scheduler: multi_step
  max_epoch: 350
  new_layers: ['classifier']
  open_layers: ['classifier']
  optim: sgd
  print_freq: 20
  seed: 1
  staged_lr: False
  start_epoch: 0
  stepsize: [150, 225, 300]
  weight_decay: 0.0005
use_gpu: True
video:
  pooling_method: avg
  sample_method: evenly
  seq_len: 15
```
